CREATE TABLE Sheet1(mysql>_create_database_aggregation; VARCHAR(10));
INSERT INTO Sheet1 (mysql>_create_database_aggregation;) VALUES 
('Query OK, 1 row affected (0.02 sec)'),
('mysql> use aggregation;'),
('Database changed'),
('mysql> create table product(product_id varchar(10) primary key not null,product_name varchar(10) not'),
(' null,'),
('ck int not null);'),
('Query OK, 0 rows affected (0.03 sec)'),
('mysql> desc product;'),
('+----------------+-------------+------+-----+---------+-------+'),
('| Field          | Type        | Null | Key | Default | Extra |'),
('+----------------+-------------+------+-----+---------+-------+'),
('| product_id     | varchar(10) | NO   | PRI | NULL    |       |'),
('| product_name   | varchar(10) | NO   |     | NULL    |       |'),
('| category       | varchar(10) | NO   |     | NULL    |       |'),
('| original_price | double      | NO   |     | NULL    |       |'),
('| selling_price  | double      | NO   |     | NULL    |       |'),
('| stock          | int         | NO   |     | NULL    |       |'),
('+----------------+-------------+------+-----+---------+-------+'),
('6 rows in set (0.00 sec)'),
('mysql> insert into product values ('P101','Laptop','Electronic',45000,49999,10), ('P102','Mobile','Electronic',12000,14999,25), ('P103','Shirt','Clothing',500,899,100), ('P104','Jeans','Clothing',800,1299,50), ('P105','Headphones','Electronic',2000,2999,30);'),
('Query OK, 5 rows affected (0.01 sec)'),
('Records: 5  Duplicates: 0  Warnings: 0'),
('mysql> select * from product;'),
('+------------+--------------+------------+----------------+---------------+-------+'),
('| product_id | product_name | category   | original_price | selling_price | stock |'),
('+------------+--------------+------------+----------------+---------------+-------+'),
('| P101       | Laptop       | Electronic |          45000 |         49999 |    10 |'),
('| P102       | Mobile       | Electronic |          12000 |         14999 |    25 |'),
('| P103       | Shirt        | Clothing   |            500 |           899 |   100 |'),
('| P104       | Jeans        | Clothing   |            800 |          1299 |    50 |'),
('| P105       | Headphones   | Electronic |           2000 |          2999 |    30 |'),
('+------------+--------------+------------+----------------+---------------+-------+'),
('#To calculate summation of selling price'),
('mysql> select sum(selling_price) from product;'),
('+--------------------+'),
('| sum(selling_price) |'),
('+--------------------+'),
('|              70195 |'),
('+--------------------+'),
('1 row in set (0.00 sec)'),
('#To calculate average of selling price'),
('mysql> select avg(selling_price) from product;'),
('+--------------------+'),
('| avg(selling_price) |'),
('+--------------------+'),
('|              14039 |'),
('+--------------------+'),
('1 row in set (0.00 sec)'),
('#To count number of records'),
('mysql> select count(*) from product;'),
('+----------+'),
('| count(*) |'),
('+----------+'),
('|        5 |'),
('+—————+'),
('#To calculate maximum stock price'),
('mysql> select max(stock) from product;'),
('+------------+'),
('| max(stock) |'),
('+------------+'),
('|        100 |'),
('+——————+'),
('#To calculate minimum stock price'),
('mysql> select min(stock) from product;'),
('+------------+'),
('| min(stock) |'),
('+------------+'),
('|         10 |'),
('+——————+'),
('#To arrange data in ascending by stock'),
('mysql> select * from product order by stock;'),
('+------------+--------------+------------+----------------+---------------+-------+'),
('| product_id | product_name | category   | original_price | selling_price | stock |'),
('+------------+--------------+------------+----------------+---------------+-------+'),
('| P101       | Laptop       | Electronic |          45000 |         49999 |    10 |'),
('| P102       | Mobile       | Electronic |          12000 |         14999 |    25 |'),
('| P105       | Headphones   | Electronic |           2000 |          2999 |    30 |'),
('| P104       | Jeans        | Clothing   |            800 |          1299 |    50 |'),
('| P103       | Shirt        | Clothing   |            500 |           899 |   100 |'),
('+------------+--------------+------------+----------------+---------------+-------+'),
('#To arrange data in descending by stock'),
('mysql> select * from product order by stock desc;'),
('+------------+--------------+------------+----------------+---------------+-------+'),
('| product_id | product_name | category   | original_price | selling_price | stock |'),
('+------------+--------------+------------+----------------+---------------+-------+'),
('| P103       | Shirt        | Clothing   |            500 |           899 |   100 |'),
('| P104       | Jeans        | Clothing   |            800 |          1299 |    50 |'),
('| P105       | Headphones   | Electronic |           2000 |          2999 |    30 |'),
('| P102       | Mobile       | Electronic |          12000 |         14999 |    25 |'),
('| P101       | Laptop       | Electronic |          45000 |         49999 |    10 |'),
('+------------+--------------+------------+----------------+---------------+-------+'),
('Group by —Used to group the rows that have same values'),
('#Count employee in each department (Group by clause)'),
('mysql> select department, count(*) as total_emp from employee group by department;'),
('+------------+-----------+'),
('| department | total_emp |'),
('+------------+-----------+'),
('| HR         |         2 |'),
('| IT         |         2 |'),
('| Finance    |         1 |'),
('+------------+-----------+'),
('#Calculate total salary per department'),
('mysql> select department, sum(salary) as total_salary from employee group by department;'),
('+------------+--------------+'),
('| department | total_salary |'),
('+------------+--------------+'),
('| HR         |        47000 |'),
('| IT         |        66000 |'),
('| Finance    |         4500 |'),
('+------------+———————+'),
('#Calculate average salary per department'),
('mysql> select department, avg(salary) as avg_salary from employee group by department;'),
('+------------+------------+'),
('| department | avg_salary |'),
('+------------+------------+'),
('| HR         | 23500.0000 |'),
('| IT         | 33000.0000 |'),
('| Finance    |  4500.0000 |'),
('+------------+——————+'),
('mysql> select department,salary,count(*) from employee group by department,salary;'),
('+------------+--------+----------+'),
('| department | salary | count(*) |'),
('+------------+--------+----------+'),
('| HR         |  40000 |        1 |'),
('| IT         |  60000 |        1 |'),
('| IT         |   6000 |        1 |'),
('| HR         |   7000 |        1 |'),
('| Finance    |   4500 |        1 |'),
('+------------+--------+----------+'),
('#Fetch records whose department is more than 1'),
('mysql> select department, count(*) as total_emp from employee group by department having count(*)>1;'),
('+------------+-----------+'),
('| department | total_emp |'),
('+------------+-----------+'),
('| HR         |         2 |'),
('| IT         |         2 |'),
('+------------+—————+'),
('#Fetch the department with total salary is greater than 8000'),
('mysql> select department,sum(salary) as total_salary from employee group by department having sum(salary)>8000;'),
('+------------+--------------+'),
('| department | total_salary |'),
('+------------+--------------+'),
('| HR         |        47000 |'),
('| IT         |        66000 |'),
('+------------+———————+'),
('#Return avg salary greater than 5000'),
('mysql> select department,avg(salary) as avg_salary from employee group by department having avg(salary)>5000;'),
('+------------+------------+'),
('| department | avg_salary |'),
('+------------+------------+'),
('| HR         | 23500.0000 |'),
('| IT         | 33000.0000 |'),
('+------------+——————+');