CREATE TABLE Sheet1(mysql>_use_ecommerce; VARCHAR(10));
INSERT INTO Sheet1 (mysql>_use_ecommerce;) VALUES 
('Reading table information for completion of table and column names'),
('You can turn off this feature to get a quicker startup with -A'),
('Database changed'),
('mysql> select * from customer;'),
('+-------------+--------+-------+------------------+---------+--------------+---------+'),
('| customer_id | name   | city  | email            | address | phone_number | pincode |'),
('+-------------+--------+-------+------------------+---------+--------------+---------+'),
('| C101        | Ayesha | Thane | ayesha@gmail.com | Almas   | 4356787534   | 400612  |'),
('+-------------+--------+-------+------------------+---------+--------------+---------+'),
('1 row in set (0.00 sec)'),
('mysql> desc customer;'),
('+--------------+--------------+------+-----+---------+-------+'),
('| Field        | Type         | Null | Key | Default | Extra |'),
('+--------------+--------------+------+-----+---------+-------+'),
('| customer_id  | varchar(5)   | NO   | PRI | NULL    |       |'),
('| name         | varchar(10)  | YES  |     | NULL    |       |'),
('| city         | varchar(10)  | YES  |     | NULL    |       |'),
('| email        | varchar(20)  | YES  |     | NULL    |       |'),
('| address      | varchar(100) | YES  |     | NULL    |       |'),
('| phone_number | varchar(10)  | NO   |     | NULL    |       |'),
('| pincode      | varchar(6)   | NO   |     | NULL    |       |'),
('+--------------+--------------+------+-----+---------+-------+'),
('7 rows in set (0.00 sec)'),
('#To insert single row'),
('mysql> insert into customer values('C102','Ariba','Mumbra','ariba@gmail.com','Zoha Apartment','2345678906','400612');'),
('Query OK, 1 row affected (0.01 sec)'),
('mysql> desc customer;'),
('+--------------+--------------+------+-----+---------+-------+'),
('| Field        | Type         | Null | Key | Default | Extra |'),
('+--------------+--------------+------+-----+---------+-------+'),
('| customer_id  | varchar(5)   | NO   | PRI | NULL    |       |'),
('| name         | varchar(10)  | YES  |     | NULL    |       |'),
('| city         | varchar(10)  | YES  |     | NULL    |       |'),
('| email        | varchar(20)  | YES  |     | NULL    |       |'),
('| address      | varchar(100) | YES  |     | NULL    |       |'),
('| phone_number | varchar(10)  | NO   |     | NULL    |       |'),
('| pincode      | varchar(6)   | NO   |     | NULL    |       |'),
('+--------------+--------------+------+-----+---------+-------+'),
('7 rows in set (0.00 sec)'),
('mysql> select * from customer;'),
('+-------------+--------+--------+------------------+----------------+--------------+---------+'),
('| customer_id | name   | city   | email            | address        | phone_number | pincode |'),
('+-------------+--------+--------+------------------+----------------+--------------+---------+'),
('| C101        | Ayesha | Thane  | ayesha@gmail.com | Almas          | 4356787534   | 400612  |'),
('| C102        | Ariba  | Mumbra | ariba@gmail.com  | Zoha Apartment | 2345678906   | 400612  |'),
('+-------------+--------+--------+------------------+----------------+--------------+---------+'),
('2 rows in set (0.00 sec)'),
('#To insert multiple rows'),
('mysql> insert into customer values('C103','Arshiya','thane','arshiya@gmail.com','grace','937261234','10654',10,'mumbai'),('C104','mannan','mumbra','mannan@gmail.com','universe','1234567890','400612',10,'goa');'),
('Query OK, 2 rows affected (0.01 sec)'),
('Records: 2  Duplicates: 0  Warnings: 0'),
('mysql> select * from customer;'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| customer_id | customer_name | city   | email             | address        | phone_number | pincode | bill | state  |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| C101        | Ayesha        | Thane  | ayesha@gmail.com  | Almas          | 4356787534   | 400612  |    0 |        |'),
('| C102        | Ariba         | Mumbra | ariba@gmail.com   | Zoha Apartment | 2345678906   | 400612  |    0 |        |'),
('| C103        | Arshiya       | thane  | arshiya@gmail.com | grace          | 937261234    | 10654   |   10 | mumbai |'),
('| C104        | mannan        | mumbra | mannan@gmail.com  | universe       | 1234567890   | 400612  |   10 | goa    |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('4 rows in set (0.01 sec)'),
('#Used alter command to change column name with change keyword'),
('mysql> alter table customer change name customer_name varchar(10) not null;'),
('Query OK, 0 rows affected (0.06 sec)'),
('Records: 0  Duplicates: 0  Warnings: 0'),
('mysql> desc customer;'),
('+---------------+--------------+------+-----+---------+-------+'),
('| Field         | Type         | Null | Key | Default | Extra |'),
('+---------------+--------------+------+-----+---------+-------+'),
('| customer_id   | varchar(5)   | NO   | PRI | NULL    |       |'),
('| customer_name | varchar(10)  | NO   |     | NULL    |       |'),
('| city          | varchar(10)  | YES  |     | NULL    |       |'),
('| email         | varchar(20)  | YES  |     | NULL    |       |'),
('| address       | varchar(100) | YES  |     | NULL    |       |'),
('| phone_number  | varchar(10)  | NO   |     | NULL    |       |'),
('| pincode       | varchar(6)   | NO   |     | NULL    |       |'),
('+---------------+--------------+------+-----+---------+-------+'),
('7 rows in set (0.00 sec)'),
('mysql> select * from customer;'),
('+-------------+---------------+--------+------------------+----------------+--------------+---------+'),
('| customer_id | customer_name | city   | email            | address        | phone_number | pincode |'),
('+-------------+---------------+--------+------------------+----------------+--------------+---------+'),
('| C101        | Ayesha        | Thane  | ayesha@gmail.com | Almas          | 4356787534   | 400612  |'),
('| C102        | Ariba         | Mumbra | ariba@gmail.com  | Zoha Apartment | 2345678906   | 400612  |'),
('+-------------+---------------+--------+------------------+----------------+--------------+---------+'),
('2 rows in set (0.00 sec)'),
('#Used alter command to add new columns'),
('mysql> alter table customer add bill int not null,add state varchar(10) not null;'),
('Query OK, 0 rows affected (0.02 sec)'),
('Records: 0  Duplicates: 0  Warnings: 0'),
('mysql> desc customer;'),
('+---------------+--------------+------+-----+---------+-------+'),
('| Field         | Type         | Null | Key | Default | Extra |'),
('+---------------+--------------+------+-----+---------+-------+'),
('| customer_id   | varchar(5)   | NO   | PRI | NULL    |       |'),
('| customer_name | varchar(10)  | NO   |     | NULL    |       |'),
('| city          | varchar(10)  | YES  |     | NULL    |       |'),
('| email         | varchar(20)  | YES  |     | NULL    |       |'),
('| address       | varchar(100) | YES  |     | NULL    |       |'),
('| phone_number  | varchar(10)  | NO   |     | NULL    |       |'),
('| pincode       | varchar(6)   | NO   |     | NULL    |       |'),
('| bill          | int          | NO   |     | NULL    |       |'),
('| state         | varchar(10)  | NO   |     | NULL    |       |'),
('+---------------+--------------+------+-----+---------+-------+'),
('9 rows in set (0.00 sec)'),
('mysql> create table demo(id int primary key not null,name varchar(10) not null);'),
('Query OK, 0 rows affected (0.01 sec)'),
('#Used alter command To drop primary key'),
('mysql> alter table demo drop primary key;'),
('Query OK, 0 rows affected (0.04 sec)'),
('Records: 0  Duplicates: 0  Warnings: 0'),
('#used alter command to To add primary key'),
('mysql> alter table demo add primary key(id);'),
('Query OK, 0 rows affected (0.03 sec)'),
('Records: 0  Duplicates: 0  Warnings: 0'),
('mysql> desc demo;'),
('+-------+-------------+------+-----+---------+-------+'),
('| Field | Type        | Null | Key | Default | Extra |'),
('+-------+-------------+------+-----+---------+-------+'),
('| id    | int         | NO   | PRI | NULL    |       |'),
('| name  | varchar(10) | NO   |     | NULL    |       |'),
('+-------+-------------+------+-----+---------+-------+'),
('2 rows in set (0.00 sec)'),
('#Used alter command to modify constraints of exsisting table'),
('mysql> alter table customer modify customer_id varchar(10) not null;'),
('Query OK, 0 rows affected (0.02 sec)'),
('Records: 0  Duplicates: 0  Warnings: 0'),
('mysql> desc customer;'),
('+---------------+--------------+------+-----+---------+-------+'),
('| Field         | Type         | Null | Key | Default | Extra |'),
('+---------------+--------------+------+-----+---------+-------+'),
('| customer_id   | varchar(10)  | NO   | PRI | NULL    |       |'),
('| customer_name | varchar(10)  | NO   |     | NULL    |       |'),
('| city          | varchar(10)  | YES  |     | NULL    |       |'),
('| email         | varchar(20)  | YES  |     | NULL    |       |'),
('| address       | varchar(100) | YES  |     | NULL    |       |'),
('| phone_number  | varchar(10)  | NO   |     | NULL    |       |'),
('| pincode       | varchar(6)   | NO   |     | NULL    |       |'),
('| bill          | int          | NO   |     | NULL    |       |'),
('| state         | varchar(10)  | NO   |     | NULL    |       |'),
('+---------------+--------------+------+-----+---------+-------+'),
('9 rows in set (0.00 sec)'),
('mysql> select * from customer;'),
('+-------------+---------------+--------+------------------+----------------+--------------+---------+------+-------+'),
('| customer_id | customer_name | city   | email            | address        | phone_number | pincode | bill | state |'),
('+-------------+---------------+--------+------------------+----------------+--------------+---------+------+-------+'),
('| C101        | Ayesha        | Thane  | ayesha@gmail.com | Almas          | 4356787534   | 400612  |    0 |       |'),
('| C102        | Ariba         | Mumbra | ariba@gmail.com  | Zoha Apartment | 2345678906   | 400612  |    0 |       |'),
('+-------------+---------------+--------+------------------+----------------+--------------+---------+------+-------+'),
('2 rows in set (0.00 sec)'),
('mysql> delete from demo;'),
('Query OK, 0 rows affected (0.00 sec)'),
('#To delete particular entry'),
('mysql> delete from customer where customer_id='C104';'),
('Query OK, 1 row affected (0.00 sec)'),
('mysql> select * from customer;'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| customer_id | customer_name | city   | email             | address        | phone_number | pincode | bill | state  |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| C101        | Ayesha        | Thane  | ayesha@gmail.com  | Almas          | 4356787534   | 400612  |    0 |        |'),
('| C102        | Ariba         | Mumbra | ariba@gmail.com   | Zoha Apartment | 2345678906   | 400612  |    0 |        |'),
('| C103        | Arshiya       | thane  | arshiya@gmail.com | grace          | 937261234    | 10654   |   10 | mumbai |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('3 rows in set (0.00 sec)'),
('mysql> desc demo;'),
('+-------+-------------+------+-----+---------+-------+'),
('| Field | Type        | Null | Key | Default | Extra |'),
('+-------+-------------+------+-----+---------+-------+'),
('| id    | int         | NO   | PRI | NULL    |       |'),
('| name  | varchar(10) | NO   |     | NULL    |       |'),
('+-------+-------------+------+-----+---------+-------+'),
('2 rows in set (0.00 sec)'),
('mysql> insert into demo values(101,'ayesha');'),
('Query OK, 1 row affected (0.00 sec)'),
('mysql> desc demo;'),
('+-------+-------------+------+-----+---------+-------+'),
('| Field | Type        | Null | Key | Default | Extra |'),
('+-------+-------------+------+-----+---------+-------+'),
('| id    | int         | NO   | PRI | NULL    |       |'),
('| name  | varchar(10) | NO   |     | NULL    |       |'),
('+-------+-------------+------+-----+---------+-------+'),
('2 rows in set (0.00 sec)'),
('mysql> select * from demo;'),
('+-----+--------+'),
('| id  | name   |'),
('+-----+--------+'),
('| 101 | ayesha |'),
('+-----+--------+'),
('1 row in set (0.00 sec)'),
('#To remove values but keep structure'),
('mysql> truncate table demo;'),
('Query OK, 0 rows affected (0.01 sec)'),
('mysql> select * from demo;'),
('Empty set (0.00 sec)'),
('mysql> desc demo;'),
('+-------+-------------+------+-----+---------+-------+'),
('| Field | Type        | Null | Key | Default | Extra |'),
('+-------+-------------+------+-----+---------+-------+'),
('| id    | int         | NO   | PRI | NULL    |       |'),
('| name  | varchar(10) | NO   |     | NULL    |       |'),
('+-------+-------------+------+-----+---------+-------+'),
('2 rows in set (0.00 sec)'),
('#To remove vales and structure'),
('mysql> drop table demo;'),
('Query OK, 0 rows affected (0.01 sec)'),
('mysql> desc demo;'),
('ERROR 1146 (42S02): Table 'ecommerce.demo' doesn't exist'),
('#Select command to retrieve values'),
('mysql> select * from customer;'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| customer_id | customer_name | city   | email             | address        | phone_number | pincode | bill | state  |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('| C101        | Ayesha        | Thane  | ayesha@gmail.com  | Almas          | 4356787534   | 400612  |    0 |        |'),
('| C102        | Ariba         | Mumbra | ariba@gmail.com   | Zoha Apartment | 2345678906   | 400612  |    0 |        |'),
('| C103        | Arshiya       | thane  | arshiya@gmail.com | grace          | 937261234    | 10654   |   10 | mumbai |'),
('+-------------+---------------+--------+-------------------+----------------+--------------+---------+------+--------+'),
('3 rows in set (0.00 sec)'),
('#Select command to retrieve only selected columns'),
('mysql> select customer_id,customer_name from customer;'),
('+-------------+---------------+'),
('| customer_id | customer_name |'),
('+-------------+---------------+'),
('| C101        | Ayesha        |'),
('| C102        | Ariba         |'),
('| C103        | Arshiya       |'),
('+-------------+---------------+'),
('3 rows in set (0.00 sec)'),
('mysql> ');