CREATE TABLE Sheet1(Column_1 VARCHAR(10));
INSERT INTO Sheet1 (Column_1) VALUES 
('12-05-26'),
('Joins—used to combine rows of multiple tables'),
('mysql> use joins;'),
('Database changed'),
('mysql> create table department(department_id int primary key not null,dept_name varchar(30) not null);'),
('Query OK, 0 rows affected (0.05 sec)'),
('mysql> desc department;'),
('+---------------+-------------+------+-----+---------+-------+'),
('| Field         | Type        | Null | Key | Default | Extra |'),
('+---------------+-------------+------+-----+---------+-------+'),
('| department_id | int         | NO   | PRI | NULL    |       |'),
('| dept_name     | varchar(30) | NO   |     | NULL    |       |'),
('+---------------+-------------+------+-----+---------+-------+'),
('2 rows in set (0.01 sec)'),
('mysql> insert into department values(1,'HR'),(2,'IT'),(3,'FINANCE'),(4,'MARKETING');'),
('Query OK, 4 rows affected (0.01 sec)'),
('Records: 4  Duplicates: 0  Warnings: 0'),
('mysql> select * from deparrtment;'),
('ERROR 1146 (42S02): Table 'joins.deparrtment' doesn't exist'),
('mysql> select * from department;'),
('+---------------+-----------+'),
('| department_id | dept_name |'),
('+---------------+-----------+'),
('|             1 | HR        |'),
('|             2 | IT        |'),
('|             3 | FINANCE   |'),
('|             4 | MARKETING |'),
('+---------------+-----------+'),
('4 rows in set (0.00 sec)'),
('mysql> create table employee(emp_id int primary key not null,emp_name varchar(30) not null,department_id int, foreign key(department_id) references department(department_id) );'),
('Query OK, 0 rows affected (0.02 sec)'),
('mysql> desc employee;'),
('+---------------+-------------+------+-----+---------+-------+'),
('| Field         | Type        | Null | Key | Default | Extra |'),
('+---------------+-------------+------+-----+---------+-------+'),
('| emp_id        | int         | NO   | PRI | NULL    |       |'),
('| emp_name      | varchar(30) | NO   |     | NULL    |       |'),
('| department_id | int         | YES  | MUL | NULL    |       |'),
('+---------------+-------------+------+-----+---------+-------+'),
('3 rows in set (0.00 sec)'),
('mysql> insert into employee values(1,'Ayesha',1),(2,'Nazmin',2),(3,'Fatima',1),(4,'Khan',null),(5,'ariba',4);'),
('Query OK, 5 rows affected (0.01 sec)'),
('Records: 5  Duplicates: 0  Warnings: 0'),
('mysql> select * from employee;'),
('+--------+----------+---------------+'),
('| emp_id | emp_name | department_id |'),
('+--------+----------+---------------+'),
('|      1 | Ayesha   |             1 |'),
('|      2 | Nazmin   |             2 |'),
('|      3 | Fatima   |             1 |'),
('|      4 | Khan     |          NULL |'),
('|      5 | ariba    |             4 |'),
('+--------+----------+---------------+'),
('5 rows in set (0.00 sec)'),
('mysql> select * from department;'),
('+---------------+-----------+'),
('| department_id | dept_name |'),
('+---------------+-----------+'),
('|             1 | HR        |'),
('|             2 | IT        |'),
('|             3 | FINANCE   |'),
('|             4 | MARKETING |'),
('+---------------+-----------+'),
('4 rows in set (0.00 sec)'),
('#INNER JOIN'),
('mysql> select emp_name,dept_name from employee inner join department on employee.department_id=department.department_id;'),
('+----------+-----------+'),
('| emp_name | dept_name |'),
('+----------+-----------+'),
('| Ayesha   | HR        |'),
('| Fatima   | HR        |'),
('| Nazmin   | IT        |'),
('| ariba    | MARKETING |'),
('+----------+-----------+'),
('4 rows in set (0.00 sec)'),
('#LEFT JOIN'),
('mysql> select emp_name,dept_name from employee left join department on employee.department_id=department.department_id;'),
('+----------+-----------+'),
('| emp_name | dept_name |'),
('+----------+-----------+'),
('| Ayesha   | HR        |'),
('| Nazmin   | IT        |'),
('| Fatima   | HR        |'),
('| Khan     | NULL      |'),
('| ariba    | MARKETING |'),
('+----------+-----------+'),
('#RIGHT JOIN'),
('mysql> select emp_name,dept_name from employee right join department on employee.department_id=department.department_id;'),
('+----------+-----------+'),
('| emp_name | dept_name |'),
('+----------+-----------+'),
('| Ayesha   | HR        |'),
('| Fatima   | HR        |'),
('| Nazmin   | IT        |'),
('| NULL     | FINANCE   |'),
('| ariba    | MARKETING |'),
('+----------+-----------+'),
('5 rows in set (0.00 sec)'),
('#FULL JOIN'),
('mysql> select emp_name,dept_name from employee full join department;'),
('+----------+-----------+'),
('| emp_name | dept_name |'),
('+----------+-----------+'),
('| Ayesha   | MARKETING |'),
('| Ayesha   | FINANCE   |'),
('| Ayesha   | IT        |'),
('| Ayesha   | HR        |'),
('| Nazmin   | MARKETING |'),
('| Nazmin   | FINANCE   |'),
('| Nazmin   | IT        |'),
('| Nazmin   | HR        |'),
('| Fatima   | MARKETING |'),
('| Fatima   | FINANCE   |'),
('| Fatima   | IT        |'),
('| Fatima   | HR        |'),
('| Khan     | MARKETING |'),
('| Khan     | FINANCE   |'),
('| Khan     | IT        |'),
('| Khan     | HR        |'),
('| ariba    | MARKETING |'),
('| ariba    | FINANCE   |'),
('| ariba    | IT        |'),
('| ariba    | HR        |'),
('+----------+-----------+'),
('20 rows in set, 1 warning (0.00 sec)'),
('#CROSS JOIN'),
('mysql> select emp_name,dept_name from employee cross join department;'),
('+----------+-----------+'),
('| emp_name | dept_name |'),
('+----------+-----------+'),
('| Ayesha   | MARKETING |'),
('| Ayesha   | FINANCE   |'),
('| Ayesha   | IT        |'),
('| Ayesha   | HR        |'),
('| Nazmin   | MARKETING |'),
('| Nazmin   | FINANCE   |'),
('| Nazmin   | IT        |'),
('| Nazmin   | HR        |'),
('| Fatima   | MARKETING |'),
('| Fatima   | FINANCE   |'),
('| Fatima   | IT        |'),
('| Fatima   | HR        |'),
('| Khan     | MARKETING |'),
('| Khan     | FINANCE   |'),
('| Khan     | IT        |'),
('| Khan     | HR        |'),
('| ariba    | MARKETING |'),
('| ariba    | FINANCE   |'),
('| ariba    | IT        |'),
('| ariba    | HR        |'),
('+----------+—————+'),
('#STORE PROCEDURE'),
('mysql> create database storeProcedure_eg;'),
('Query OK, 1 row affected (0.00 sec)'),
('mysql> use storeProcedure_eg;'),
('Database changed'),
('mysql> create table employee(emp_id int primary key not null,emp_name varchar(30) not null,department varchar(20) not null,salary int );'),
('Query OK, 0 rows affected (0.01 sec)'),
('mysql> insert into employee values(1,'Ayesha','IT',10000);'),
('Query OK, 1 row affected (0.00 sec)'),
('mysql> DELIMITER //'),
('mysql> '),
('mysql> CREATE PROCEDURE GetEmployees()'),
('    -> BEGIN'),
('    ->     SELECT * FROM Employee;'),
('    -> END //'),
('Query OK, 0 rows affected (0.04 sec)'),
('mysql> '),
('mysql> DELIMITER ;'),
('mysql> '),
('mysql> call GetEmployees();'),
('+--------+----------+------------+--------+'),
('| emp_id | emp_name | department | salary |'),
('+--------+----------+------------+--------+'),
('|      1 | Ayesha   | IT         |  10000 |'),
('+--------+----------+------------+————+'),
('1 row in set (0.00 sec)'),
('#With IN Parameter'),
('mysql> DELIMITER //'),
('mysql> '),
('mysql> CREATE PROCEDURE GetEmployeeByDept1(IN dept_name VARCHAR(30))'),
('    -> BEGIN'),
('    ->     SELECT * '),
('    ->     FROM Employee'),
('    ->     WHERE department = dept_name;'),
('    -> END //'),
('Query OK, 0 rows affected (0.00 sec)'),
('mysql> '),
('mysql> DELIMITER ;'),
('mysql> call GetEmployeeByDept1('IT');'),
('+--------+----------+------------+--------+'),
('| emp_id | emp_name | department | salary |'),
('+--------+----------+------------+--------+'),
('|      1 | Ayesha   | IT         |  10000 |'),
('+--------+----------+------------+--------+'),
('1 row in set (0.00 sec)'),
('#Multiple IN parameter'),
('mysql> DELIMITER //'),
('mysql> '),
('mysql> CREATE PROCEDURE AddEmployee('),
('    ->     IN  id INT,'),
('    ->     IN name VARCHAR(50),'),
('    ->     IN dept VARCHAR(50),'),
('    ->     IN salary INT'),
('    -> )'),
('    -> BEGIN'),
('    ->     INSERT INTO Employee(emp_id, emp_name, department, salary)'),
('    ->     VALUES(id, name, dept, salary);'),
('    -> END //'),
('Query OK, 0 rows affected (0.00 sec)'),
('mysql> '),
('mysql> DELIMITER ;'),
('mysql> call AddEmployee(3,'Arshiya','HR',12000);'),
('Query OK, 1 row affected (0.01 sec)'),
('mysql> select * from employee;'),
('+--------+----------+------------+--------+'),
('| emp_id | emp_name | department | salary |'),
('+--------+----------+------------+--------+'),
('|      1 | Ayesha   | IT         |  10000 |'),
('|      2 | khan     | CS         |  10000 |'),
('|      3 | Arshiya  | HR         |  12000 |'),
('+--------+----------+------------+--------+'),
('#With OUT Parameter'),
('mysql> DELIMITER //'),
('mysql> '),
('mysql> CREATE PROCEDURE GetEmployeeCount(OUT total INT)'),
('    -> BEGIN'),
('    ->     SELECT COUNT(*) INTO total'),
('    ->     FROM Employee;'),
('    -> END //'),
('Query OK, 0 rows affected (0.01 sec)'),
('mysql> '),
('mysql> DELIMITER ;'),
('mysql> call GetEmployeeCount(@total);'),
('Query OK, 1 row affected (0.00 sec)'),
('mysql> select @total;'),
('+--------+'),
('| @total |'),
('+--------+'),
('|      3 |'),
('+--------+');