CREATE TABLE Sheet1(mysql>_/*_Create_a_table_with_named_Feedback VARCHAR(10));
INSERT INTO Sheet1 (mysql>_/*_Create_a_table_with_named_Feedback) VALUES 
('   /*> '),
('   /*> with attributes: ● FeedbackID (Primary Key) '),
('   /*> '),
('   /*> ● StudentID (Foreign key) '),
('   /*> '),
('   /*> ● Date '),
('   /*> '),
('   /*> ● InstructorName '),
('   /*> '),
('   /*> ● Feedback */'),
('    -> '),
('    -> ;'),
('Query OK, 0 rows affected (0.00 sec)'),
('mysql> create database student_management_sys;'),
('Query OK, 1 row affected (0.01 sec)'),
('mysql> use student_management_sys;'),
('Database changed'),
('mysql> create table student(student_id varchar(10) primary key not null,name varchar(20) ,age int, phone_no varchar(10));'),
('Query OK, 0 rows affected (0.01 sec)'),
('mysql> desc student;'),
('+------------+-------------+------+-----+---------+-------+'),
('| Field      | Type        | Null | Key | Default | Extra |'),
('+------------+-------------+------+-----+---------+-------+'),
('| student_id | varchar(10) | NO   | PRI | NULL    |       |'),
('| name       | varchar(20) | YES  |     | NULL    |       |'),
('| age        | int         | YES  |     | NULL    |       |'),
('| phone_no   | varchar(10) | YES  |     | NULL    |       |'),
('+------------+-------------+------+-----+---------+-------+'),
('4 rows in set (0.00 sec)'),
('mysql> create table Feedback(Feedback_id varchar(10) primary key not null, student_id varchar(10) not null, date date not null, instructor_name varchar(20'),
('    -> ) not null ,feedback varchar(100) not null, foreign key (student_id) references student (student_id));'),
('Query OK, 0 rows affected (0.02 sec)'),
('mysql> desc Feedback;'),
('+-----------------+--------------+------+-----+---------+-------+'),
('| Field           | Type         | Null | Key | Default | Extra |'),
('+-----------------+--------------+------+-----+---------+-------+'),
('| Feedback_id     | varchar(10)  | NO   | PRI | NULL    |       |'),
('| student_id      | varchar(10)  | NO   | MUL | NULL    |       |'),
('| date            | date         | NO   |     | NULL    |       |'),
('| instructor_name | varchar(20)  | NO   |     | NULL    |       |'),
('| feedback        | varchar(100) | NO   |     | NULL    |       |'),
('+-----------------+--------------+------+-----+---------+-------+'),
('5 rows in set (0.00 sec)');