CREATE TABLE Sheet1(Column_1 VARCHAR(10));
INSERT INTO Sheet1 (Column_1) VALUES 
('/* Lab 2: Database Schema: Consider a simple database with one tables: BankAccount '),
('BankAccount Table: ● Columns: account_id (Primary Key), account_holder_name, account_balance'),
(' Task 1: Insert Data Write an SQL INSERT statement to insert data into the BankAccount table'),
('. Task 2: Retrieving Data Write an SQL SELECT statement to retrieve the account_holder_name and account_balance of all account holders from the BankAccount table. '),
('Task 3: Filtering Data Write an SQL SELECT statement to retrieve the account_holder_name and account_balance where the account_balance is more than 30,000.'),
(' Task 4: Updating Data Write an SQL UPDATE statement to change the account_balance of the account holder whose ID is 101. */'),
('mysql> create database bank;'),
('Query OK, 1 row affected (0.01 sec)'),
('mysql> use bank;'),
('Database changed'),
('mysql> create table BankAccount(account_id varchar(10) primary key not null,account_holder_name varchar(20) not null,account_balance int not null);'),
('Query OK, 0 rows affected (0.04 sec)'),
('mysql> desc BankAccount;'),
('+---------------------+-------------+------+-----+---------+-------+'),
('| Field               | Type        | Null | Key | Default | Extra |'),
('+---------------------+-------------+------+-----+---------+-------+'),
('| account_id          | varchar(10) | NO   | PRI | NULL    |       |'),
('| account_holder_name | varchar(20) | NO   |     | NULL    |       |'),
('| account_balance     | int         | NO   |     | NULL    |       |'),
('+---------------------+-------------+------+-----+---------+-------+'),
('3 rows in set (0.00 sec)'),
('#Task 1: Insert Data Write an SQL INSERT statement to insert data into the BankAccount table'),
('mysql> insert into BankAccount values('A101','Ayesha',20000),('A102','Ansari',30000),('A103','Mariyam',10000);'),
('Query OK, 3 rows affected (0.01 sec)'),
('Records: 3  Duplicates: 0  Warnings: 0'),
('mysql> insert into BankAccount values('A104','fatima',15000);'),
('Query OK, 1 row affected (0.00 sec)'),
('mysql> select * from BankAccount;'),
('+------------+---------------------+-----------------+'),
('| account_id | account_holder_name | account_balance |'),
('+------------+---------------------+-----------------+'),
('| A101       | Ayesha              |           20000 |'),
('| A102       | Ansari              |           30000 |'),
('| A103       | Mariyam             |           10000 |'),
('| A104       | fatima              |           15000 |'),
('+------------+---------------------+-----------------+'),
('4 rows in set (0.00 sec)'),
('mysql> insert into BankAccount values('A105','Nazmin',45000);'),
('Query OK, 1 row affected (0.00 sec)'),
('mysql> insert into BankAccount values('A106','Zuveriya',50000);'),
('Query OK, 1 row affected (0.00 sec)'),
('#Task 2: Retrieving Data Write an SQL SELECT statement to retrieve the account_holder_name and account_balance of all account holders from the BankAccount table. '),
('mysql> select * from BankAccount;'),
('+------------+---------------------+-----------------+'),
('| account_id | account_holder_name | account_balance |'),
('+------------+---------------------+-----------------+'),
('| A101       | Ayesha              |           20000 |'),
('| A102       | Ansari              |           30000 |'),
('| A103       | Mariyam             |           10000 |'),
('| A104       | fatima              |           15000 |'),
('| A105       | Nazmin              |           45000 |'),
('| A106       | Zuveriya            |           50000 |'),
('+------------+---------------------+-----------------+'),
('6 rows in set (0.00 sec)'),
('#Task 3: Filtering Data Write an SQL SELECT statement to retrieve the account_holder_name and account_balance where the account_balance is more than 30,000.'),
('mysql> select account_holder_name ,account_balance from BankAccount where account_balance>30000;'),
('+---------------------+-----------------+'),
('| account_holder_name | account_balance |'),
('+---------------------+-----------------+'),
('| Nazmin              |           45000 |'),
('| Zuveriya            |           50000 |'),
('+---------------------+-----------------+'),
('2 rows in set (0.00 sec)'),
('#Task 4: Updating Data Write an SQL UPDATE statement to change the account_balance of the account holder whose ID is 101'),
('mysql> update BankAccount set account_balance=30000 where account_id='A101';'),
('Query OK, 1 row affected (0.00 sec)'),
('Rows matched: 1  Changed: 1  Warnings: 0'),
('mysql> select * from BankAccount;'),
('+------------+---------------------+-----------------+'),
('| account_id | account_holder_name | account_balance |'),
('+------------+---------------------+-----------------+'),
('| A101       | Ayesha              |           30000 |'),
('| A102       | Ansari              |           30000 |'),
('| A103       | Mariyam             |           10000 |'),
('| A104       | fatima              |           15000 |'),
('| A105       | Nazmin              |           45000 |'),
('| A106       | Zuveriya            |           50000 |'),
('+------------+---------------------+-----------------+'),
('6 rows in set (0.00 sec)'),
('mysql> ');